### ISSUE TITLE
Update production zip

### ISSUE THREAD

**Issue by matthewcooper** [jamwaffles/optiplower#1]
Hello 

Great solution thank you

Can you update the gerber.zip to the new SMD version. I also notice that items U3 to U6 are missing from the BOM

(I have tried to sort this out but KiCAD not a bit of software I open much)

**Comment by jamwaffles** [comment]
I've just pushed the latest SMD gerbers. I've also added the ATTiny (`U3`) to the BOM, although I'm not sure what you mean when referring to `U4`, `U5` and `U6` as `U4` is definitely in the BOM, and `U5` and `U6` don't exist?

**Comment by jamwaffles** [comment]
Ah, were you looking at the PCB screenshots in the README? I've just updated those to the most recent SMD version. The non-existent `U*` parts were alternative footprints as I wasn't sure what I could source at the time.

**Comment by matthewcooper** [comment]
Yes, it was the old version thank you for the quick fix.
