### ISSUE TITLE
input power supply requirements

### ISSUE THREAD

**Issue by jensvanhoof86** [jamwaffles/optiplower#2]
Hi!

The project looks great and exactly what I'm looking for.
What would be the voltage and current limit for the industrial power supply at the input of the PCB?

I have a 28VDC source I'd like to use but I'm not sure if that would work?

**Comment by jamwaffles** [comment]
Hey, thanks for the interest! The circuit is centered around the XL4015 which, according to its [datasheet](https://www.xlsemi.com/datasheet/XL4015-EN.pdf), has an input voltage up to 36V so I think you should be just fine with 28V input.

**Comment by jamwaffles** [comment]
Closing as resolved,
