### ISSUE TITLE
pin swap in documentation (power out)

### ISSUE THREAD

**Issue by jensvanhoof86** [jamwaffles/optiplower#4]
Hi,

The connection diagram (white background image) for the output  connector is not correct. On your drawing the outer connections are marked as +19.5V, followed by GND and SENSE in the middle. 

It seems however that GND is on the outside, then followed by +19.5V. It is correctly displayed in the board screenshot where the net names are displayed. There it is clear that GND is pin 1 and 5, rather than 2 and 4.

**Comment by jamwaffles** [comment]
Agh I'm really sorry about that. Just pushed a fix to master! Thanks for pointing it out.
