### ISSUE TITLE
programming the Attiny25, wiring

### ISSUE THREAD

**Issue by jensvanhoof86** [jamwaffles/optiplower#5]
Question, how did you connect your USBASP to your PCB? Did you just solder 6 wires to the leads of the SMD chip or did you program it before soldering it to the board?

**Comment by jamwaffles** [comment]
I used a programming clip like this:

![image](https://github.com/jamwaffles/optiplower/assets/800791/43c0b8ff-c21a-48fe-9739-913c62bf01b1)

Search eBay for "soic clip" and you should find something similar.

**Comment by jensvanhoof86** [comment]
thanks a lot! I've just ordered one.

**Comment by jamwaffles** [comment]
Great! I'll close this issue as resolved then :)
